name: CI

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v2
      - name: YAML Lint
        uses: actionshub/yamllint@v1.0.0
